# Generated by Django 3.2.21 on 2023-09-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('adj_close', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_price',
            },
        ),
    ]
